### ISSUE TITLE
In GeoData 0.3.2, Error: got unsupported keyword argument "usercrs" in GDALarray()

### ISSUE THREAD

**Issue by vlandau** [rafaqz/GeoData.jl#114]
I think this is as simple as a kwarg needing to be updated in the source code to reflect the docs (change mappedcrs to usercrs?) in the `GDALarray` function. Here's the output I'm getting when trying to use `usercrs`:
```julia
julia> GDALarray(file_path; usercrs = EPSG(4326))
ERROR: MethodError: no method matching GDALarray(::ArchGDAL.RasterDataset{Float64,ArchGDAL.Dataset}, ::String, ::Nothing; usercrs=EPSG(4326))
Closest candidates are:
  GDALarray(::ArchGDAL.RasterDataset, ::Any, ::Any; crs, mappedcrs, dims, refdims, name, metadata, missingval) at /root/.julia/packages/GeoData/aA5LH/src/sources/gdal.jl:108 got unsupported keyword argument "usercrs"
  GDALarray(::ArchGDAL.RasterDataset, ::Any) at /root/.julia/packages/GeoData/aA5LH/src/sources/gdal.jl:108 got unsupported keyword argument "usercrs"
```

**Comment by rafaqz** [comment]
Yeah `usercrs` is `mappedcrs` now to unify the syntax for `Mapped` and `Projected` (ie netcdf and gdal)

**Comment by vlandau** [comment]
Okay makes sense. I guess the docs just need to be updated.

**Comment by rafaqz** [comment]
Yeah sorry maybe I missed those

**Comment by vlandau** [comment]
Ha! Turns out you likely didn't miss it. I assumed that the stable page contained docs for 0.3.2, but looks like those docs weren't created so it was pointing to 0.2.1 :upside_down_face: sorry about that!

**Comment by rafaqz** [comment]
Oh right that's a good catch tho! I mussed have messed up the change to github workflows.

**Comment by vlandau** [comment]
Alright sounds good! I'll go ahead and close now. Thanks!
