### ISSUE TITLE
Plots aspect_ratio=1

### ISSUE THREAD

**Issue by mauro3** [rafaqz/GeoData.jl#125]
Should the plotting aspect_ratio default to 1?  I think it is for lat-lon but not otherwise.

**Comment by rafaqz** [comment]
Plots are only defined for Lat/Lon (although were in the process of expanding this a bit). 

Otherwise youre getting generic DimentionalData.jl recipes.

**Comment by rafaqz** [comment]
Also see #106. You will be able to extent geo specific X/Y/Z dimensions by inheriting from `GeoXDim/GeoYDim/GeoZDim` using the `@dim` macro. For these, heatmaps are the default and the aspect ratio is fixed, and hopefully we can get plots looking pretty good out of the box.
