### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by mauro3** [rafaqz/GeoData.jl#131]
Could you tag a new release?  That way I can make use of DimensionalData 0.16.  Thanks!

**Comment by rafaqz** [comment]
Oh right sorry. But HDF5 has introduced a bug in SMAP (that isn't in CI) so I'll wait to fix it to tag a version. Hopefully tomorrow!

**Comment by rafaqz** [comment]
0.3.4 should be available soon.

**Comment by rafaqz** [comment]
registrator seems to be broken right now so not sure when this will come through

**Comment by mauro3** [comment]
No worries. x-ref https://github.com/JuliaRegistries/Registrator.jl/issues/320

**Comment by mauro3** [comment]
Ha, fixed already!
