### ISSUE TITLE
Where did GDALarray go?

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/GeoData.jl#138]
Hi, I just visited this package again after some time and don't know how to lazily load tiffs anymore after updating to 0.3.5. Earlier, this was done via GDALarray, but I can't find it anymore (GDALarray not defined). Also I'm thinking about whether one could improve the API for simple minds like me, providing simple entry functions like read or read_lazy, which just take a string and do the rest for me (read, load, open, each for string, are the first three words coming to my mind when I want to open stuff, but here, this doesn't lead far). Sorry for the informal issue :)

**Comment by rafaqz** [comment]
You have to `import ArchGDAL`.

GeoData uses Requires.jl because often you only need to load NCDatasets or GDAL.jl or HDF5.jl, not all of them

**Comment by maxfreu** [comment]
Thanks! And sorry, I shouldnt have posted late night...
