### ISSUE TITLE
Handling of Grids

### ISSUE THREAD

**Issue by Balinus** [rafaqz/GeoData.jl#14]
Might be a useful resource! 
https://github.com/gaelforget/MeshArrays.jl

**Comment by rafaqz** [comment]
That does looks interesting. What would you use it for? 

I'm an ecologist - mostly I use pretty simple EPSG 4326 grids lol...

**Comment by Balinus** [comment]
hehe! 

Well, it seems to take care of grids and physical quantities between grid cells. After some reading though, I think it only handles global models (GCMs)? @gaelforget might give some infos?
