### ISSUE TITLE
Can't locate the documents for the latest v0.4.5

### ISSUE THREAD

**Issue by melodyjulia** [rafaqz/GeoData.jl#179]
Does the stable docs refer to the latest v0.4.5? Thanks.

**Comment by rafaqz** [comment]
Oh sorry you're right! the docs are old. They must have stopped building properly somehow. I will try to fix.

**Comment by felixcremer** [comment]
According to the documentation of [Documenter.jl](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions) you should add the DocumenterKey to the TagBot github action, so that TagBot could trigger the documentation workflow.

**Comment by rafaqz** [comment]
@melodyjulia you can use the dev docs for now. The main docs should be updated fairly soon.

Also note there are a lot of major changes and additional methods being added soon with the next PR, that also includes a lot of updates to the docs.
