### ISSUE TITLE
When length(dvar)==1

### ISSUE THREAD

**Issue by Mattriks** [rafaqz/GeoData.jl#39]
I'm trying out GeoData.jl (master). I have a NetCDF file with 4 dims (lat,lon,time, and lev). lev only has 1 level (Vertical=20000.0).
```julia
using NCDatasets
ds = Dataset(filename)
dvar = ds["lev"] # length(dvar)==1
dvar[2]

NetCDF error: NetCDF: Index exceeds dimension bound (NetCDF error code: -40)
```
In GeoData, that error happens on [this line](https://github.com/rafaqz/GeoData.jl/blob/f6f61e8e31294d94bcbceb77c1cc9d0b1f224dbe/src/sources/ncdatasets.jl#L241).
I get the error with commit 9c2f79f, but not with commit 309aa76 (because of the correction in L240, which I know is necessary).

**Comment by rafaqz** [comment]
Ok that's just a typo, those lines should be inside the length check. Fixed on master.

I hadn't tested for dim of length 1.
