### ISSUE TITLE
Save back to tiff, netcdf, etc

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/GeoData.jl#4]

**Comment by Balinus** [comment]
Just pointing that the NCDatasets.jl framework for creating netcdf file is quite interesting.

**Comment by rafaqz** [comment]
Want to try writing an implementation? It would be great to be able to save from here, but I don't really have the bandwidth to do it at the moment.

`src/sourcese/ncdatasets.jl` has a commented out first attempt if you are interested.

**Comment by Balinus** [comment]
Will try if I find time. New job here and also very low free time sadly !

**Comment by rafaqz** [comment]
This works now :)
