### ISSUE TITLE
GrowthMaps.jl and Dispersal.jl workflow

### ISSUE THREAD

**Issue by jamesmaino** [rafaqz/GeoData.jl#50]
I was thinking a little bit more about the aggregate function and there are two things on my wish list.

1) It would be great if we could dissaggregate (i.e. upsample) so we can retrieve the previous grid size (for coarse resolutions). This would allow us to play around with the establishment parameters and explore the implications in spread, using the same grid cell sizes. 

2) We can currently aggregate in space, but it would also be good to aggregate in time. We might want to aggregate across years, or across months, so all you would have to do is pass an aggregation vector (you could probably think up a better way with units, but for example, (1, 1, 1, 2, 2, 2, 2) would aggregate the the first four and the last four entries in the stack).

**Comment by rafaqz** [comment]
yeah upsampling would be good to have.

You should be able to aggregate the time dimension already, it's totally abstract.

**Comment by rafaqz** [comment]
these are implemented now
