### ISSUE TITLE
Selector problems with reversed dims

### ISSUE THREAD

**Issue by Mattriks** [rafaqz/GeoData.jl#56]
I tried to extract time series from an ocean dataset e.g. [ersstv5.nc](https://psl.noaa.gov/data/gridded/data.noaa.ersst.v5.html) that has `Lat = Float32[88.0, 86.0, …, -86.0, -88.0]`.  The point 100°E, 40°N is clearly land, but extracting this point shows ocean temperatures:

```julia
sst = NCDstack("ersstv5.mnmean.nc")[:sst]
sst[Lat(At(40)), Lon(At(100))]

Float32[13.2772, 14.0097, 13.6713,   …  11.1825, 11.3001, 12.3442]
```

And the reflected point (which is in ocean) has all missing values:
```julia
sst[Lat(Near(-40)), Lon(Near(100))]

Float32[-9.96921f36, -9.96921f36, -9.96921f36,  …  -9.96921f36, -9.96921f36, -9.96921f36]
```

**Comment by rafaqz** [comment]
Yep I'm just in the process of trying to track down the last of these bugs.

 Can you upload the file somewhere? That's probably the easiest way to fix this.

**Comment by Mattriks** [comment]
ftp://ftp.cdc.noaa.gov/Datasets/noaa.ersst.v5/sst.mon.ltm.1981-2010.nc   (1mb)

**Comment by rafaqz** [comment]
Thanks. It plots upside down too. My tests are are all with files with forward order latitudes, thanks for catching this. There's a lot of detail to getting this all right for every format...

**Comment by rafaqz** [comment]
Ok fixed :) 

I'll push it through sometime today.

**Comment by rafaqz** [comment]
Ok that's on master now. Let me know any other issues you have, I'm keen to make a release this week.

**Comment by rafaqz** [comment]
And by the way - for some reason NCDatasets,jl is not picking up the missing value in that file.

You can set it manually by passing the kwarg for the array constructor to the stack:
```julia
A = NCDstack(file; childkwargs=(missingval=-9.96921f36,))[:sst]
```

And convert it to `missing` with `replace_missing(A)` if you need to.
