### ISSUE TITLE
Wrap gdal warp in a general method

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/GeoData.jl#68]
https://discourse.julialang.org/t/help-request-using-archgdal-gdalwarp-for-resampling-a-raster-dataset/47039

@vlandau have a go if you like, ping me with any help you need.

Checkout https://github.com/JuliaGeo/GeoFormatTypes.jl for how crs is wrapped as passed to ArchGDAL.

We could maybe just reuse the existing `reproject` method? But applied to the array so it will reproject both the data and the dim. Not sure if that's the clearest. The gdalwarp docs say it does "mosaicing, reprojecting and warping".

There are already methods to reproject the dimensions here https://github.com/rafaqz/GeoData.jl/blob/master/src/reproject.jl

**Comment by vlandau** [comment]
Thinking about the parameters we would need -- we could do something simple like:
- input raster (a GeoArray?)

And:
- output CRS (or wkt)
- output resolution
**OR**
- snap raster (and output crs and resolution can be grabbed from it). Pixels in the output raster will line be aligned with those in the snap raster. This will come in handy if you need to do raster algebra with layers that don't line up perfectly.

So maybe two methods? `resample(input::GeoArray, crs::CRS, resolution::Number)` and `resample(input::GeoArray, snap_raster::GeoArray)`

**Comment by rafaqz** [comment]
That sounds pretty spot on to me. Passing in another `GeoArray` to snap to would be really slick. `resample` is a good method name too.

If crs is a GeoFormatTypes.jl wrapper you don't have to know if it's wkt or proj etc they will just work.
