### ISSUE TITLE
Cannot subset SMAP data by Lon Lat

### ISSUE THREAD

**Issue by jamesmaino** [rafaqz/GeoData.jl#78]
Minimal reproducible example:

```julia
smapfolder = "D:/SMAP/SMAP_L4_SM_gph_v4"
seriesall = SMAPseries(smapfolder)
aus   = Lon(Between((80.0, 160.0))), Lat(Between((-50.0, 10.0)))
seriesall[Ti(1)][:land_fraction_wilting][aus...] |> plot
````

```julia

MethodError: no method matching isless(::Float64, ::HDF5Attribute)
Closest candidates are:
  isless(!Matched::Missing, ::Any) at missing.jl:87
  isless(::Float64, !Matched::Float64) at float.jl:465
  isless(::AbstractFloat, !Matched::AbstractFloat) at operators.jl:165
  ...
in top-level scope at establishment.jmd:48
in getindex at DimensionalData\IHaNW\src\array.jl:100
in dims2indices at DimensionalData\IHaNW\src\primitives.jl:133 
in dims2indices at DimensionalData\IHaNW\src\primitives.jl:133 
in dims2indices at DimensionalData\IHaNW\src\primitives.jl:144 
in _dims2indices at DimensionalData\IHaNW\src\primitives.jl:149
in macro expansion at DimensionalData\IHaNW\src\primitives.jl:149 
in _dims2indices at DimensionalData\IHaNW\src\primitives.jl:194 
in sel2indices at DimensionalData\IHaNW\src\selector.jl:215 
in sel2indices at DimensionalData\IHaNW\src\selector.jl:250 
in sel2indices at DimensionalData\IHaNW\src\selector.jl:274 
in between at DimensionalData\IHaNW\src\selector.jl:422
in between at DimensionalData\IHaNW\src\selector.jl:434
in between at DimensionalData\IHaNW\src\selector.jl:457
in <= at base\operators.jl:326
in < at base\operators.jl:277
```

**Comment by rafaqz** [comment]
Yeah we should make this abstract. see #70 

You have to specify the correct nesting of getindex:
```
seriesall[Ti(1)][:land_fraction_wilting][aus...] |> plot
```

**Comment by rafaqz** [comment]
I can't replicate this - so I think it may be in an older version. I just bumped the DimensionalData.jl version in Dispersal.jl, which I had been locked at 0.12. See if update fixes that now.

![works](https://user-images.githubusercontent.com/2534009/97830442-1649e580-1d21-11eb-8f3e-b27657262349.png)

**Comment by jamesmaino** [comment]
Still locked

Status `C:\Users\james\.julia\environments\v1.5\Project.toml`
  [c9ce4bd3] ArchGDAL v0.5.2 `
https://github.com/yeesian/ArchGDAL.jl.git#master`
  [c52e3926] Atom v0.12.24
  [b5f6e96a] Biosecurity v0.1.0 `
https://github.com/cesaraustralia/Biosecurity.jl#master`
  [ad839575] Blink v0.12.3
  [336ed68f] CSV v0.7.7
  [35d6a980] ColorSchemes v3.10.1
  [5ae59095] Colors v0.12.4
  [a93c6f00] DataFrames v0.21.8
  [1313f7d8] DataFramesMeta v0.5.1
  [0703355e] DimensionalData v0.12.1
  [8797f018] Dispersal v0.1.0 `
https://github.com/cesaraustralia/Dispersal.jl#master`
  [a5dba43e] DynamicGrids v0.10.8
  [db222a54] DynamicGridsGtk v0.5.1
  [3ccff026] DynamicGridsInteract v0.3.3
  [bf96fef3] FieldMetadata v0.3.0
  [4c728ea3] Flatten v0.3.5
  [add2ef01] GDAL v1.1.5
  [9b6fcbb8] GeoData v0.2.0
  [a252ced4] GrowthMaps v0.1.2
  [f67ccb44] HDF5 v0.13.6
  [6218d12a] ImageMagick v1.1.6
  [e5e0dc1b] Juno v0.8.4
  [85f8d34a] NCDatasets v0.10.4
  [91a5bcdd] Plots v1.7.3
  [efcf1570] Setfield v0.7.0
  [40c74d1a] TableView v0.6.1
  [1986cc42] Unitful v1.5.0
  [42071c24] UnitfulRecipes v1.0.0
  [ade2ca70] Dates
  [10745b16] Statistics



*James Maino | Senior Research Scientist*

cesar | Predictive Modelling

293 Royal Parade, Victoria 3052, Australia

*T: *0400 150 564  <0400150564> *E: *jamesmaino@gmail.com
<james.maino@unimelb.edu.au>
