### ISSUE TITLE
Conflicting identifiers: `NCDatasets.name` and `GeoData.name`

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/GeoData.jl#81]
Loading the two packages produces this warning. Could it be a problem since the two packages are meant to be used together?

```julia
julia> using NCDatasets, GeoData
WARNING: using NCDatasets.name in module GeoData conflicts with an existing identifier.
```

**Comment by rafaqz** [comment]
It's just a warning, not really an issue. A lot of packages export `name`. And GeoData.jl is just reexporting `name` from imensionalData.jl.

Basically it's saying you have to use `GeoData.name` and NCDatasets.name. You can always use `import` instead if you don't want to see it.

**Comment by ali-ramadhan** [comment]
Fair enough. If it's just a re-export then I suppose it's an empty warning (and there's not much that can be done about it).
