### ISSUE TITLE
dimkeys without bounds attrib

### ISSUE THREAD

**Issue by Mattriks** [rafaqz/GeoData.jl#84]
I've encountered this a few times, where a netcdf file has some `dimkeys` with and without a `bounds` attrib, which causes an error in [this line](https://github.com/rafaqz/GeoData.jl/blob/ae7cd8f6bfeb2f19adeee28ad6c1b95f82d1f05c/src/sources/ncdatasets.jl#L43). Suggest changing the line to something like:
```julia
 boundskeys = [dataset[k].attrib["bounds"] for k in dimkeys if haskey(dataset[k].attrib, "bounds")] 
```

**Comment by rafaqz** [comment]
Oh thanks. Want to put that in a PR?
