### ISSUE TITLE
GDALarray doesn't load lazily

### ISSUE THREAD

**Issue by maxfreu** [rafaqz/GeoData.jl#89]
Hi! When I'm loading a large image via GDALarray, my RAM gets flooded. I expected it to only read the parts I index into with ranges.

```julia
using ArchGDAL
using GeoData
img = GeoData.GDALarray("large file");

# Result:
# ┌ Warning: No data value from GDAL -1.0e10 is not convertible to data type UInt16. `missingval` is probably # incorrect.
# └ @ GeoData ~/.julia/packages/GeoData/Vnpza/src/sources/gdal.jl:269

# RAM flooded
```

julia v1.5.0
ArchGDAL v0.5.2
GeoData v0.2.1

Maybe the strange block size plays a role?
```
Size is 21171, 67760
...
Band 1 Block=21171x1 Type=UInt16, ColorInterp=Red
...
```

EDIT: I just noticed with a different file which barely fits into memory, that when I call `show(img)` the RAM usage drops temporarily, then I get the printout, and then it goes up again.

**Comment by rafaqz** [comment]
Ok interesting. I don't actually test memory use anywhere yet (but we should), and I rarely use tiff files over a few hundred MB. But in theory that should work. `GDALarray` shouldn't load any array data, or that's a bug.

We have to load the ArchGDAL.RasterDataset to know anything about the file for `GDALarray` (like how big it is, how many dimensions it has etc). I assumed that that didn't actually load data until you index into it, but I may be wrong.

That happens here:
https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/gdal.jl#L90

Which then opens the dataset which is here in ArchGDAL:

https://github.com/yeesian/ArchGDAL.jl/blob/c22481854e3dfce16070d8b379de151dbbcf39a0/src/raster/array.jl#L27

and passes it to:

https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/gdal.jl#L96

Then closes it again. Somewhere in that chain is your problem. GeoData.jl mostly does things like this in that phase:
https://github.com/rafaqz/GeoData.jl/blob/master/src/sources/gdal.jl#L263

But my understanding was that they are just wrappers to the data, which isn't actually loaded until you call `read`. Maybe `show` is being called in the REPL? We should probably write a custom show method that doesn't load the data.

Try to define:
`Base.show(io::IO, GDALarray)` = nothing

**Comment by rafaqz** [comment]
See #90

You can do:
`] add GeoArray#no_show`

To see if it works for you.

**Comment by maxfreu** [comment]
Setting show to nothing helps indeed! Now I can index into a 50GB tiff without problems. However I wonder what the fastest way for storing and reading the data is (I'm thinking of block size, pixel or band interleaved storage, compression algorithm & file type). But I think this is close :)

**Comment by rafaqz** [comment]
Great! I never actually tried that on a file that big I'm glad it just works!! I'll get that PR merged too. You will be able to show the dims and filename and not worry about this - it just wont show the array data.

For blocking, [DiskArrays.jl](https://github.com/meggart/DiskArrays.jl) should handle all of that under the hood for ArchGDAL.jl. @meggart has done amazing work to make that happen, and maybe has some comments on how we should proceed.

The aim of GeoData.jl is to wrap spatial data in a standardised easy to use interface on the user end, but to avoid low-level work where possible to keep things modular. So DiskArrays standardizes the disk interface - chunking etc.

But GeoData.jl should do more to make information from DiskArrays.jl available from the GDALarray object if you need it anywhere - like if you need to know chunk sizes. I always intended that but there is only so much time for this... and I mostly work with huge time-series of small files, so have different problems to handle. But if you let me know what you need from there I can make sure it's supported and available from the `GDALarray` object.

**Comment by rafaqz** [comment]
Also writing to a file that big isn't supported yet in GeoData. Well need a way to load, modify and write chunks one at a time - again this will be about coordinating things properly with DiskArrays.

I can help with making it work in the context of GeoData once it's clear what you need to do if you were just using ArchGDAL directly, but its really not my field of expertise. @meggart will know a lot more.

**Comment by maxfreu** [comment]
Ok first things first: The initial issue is solved, so this can be closed.

Now the messy part:
Actually I dont have a real application at the moment. In general I work on classifying satellite and aerial images via deep learning. Currently I'm using PyTorch for that and don't see that changing yet; I hope to call it via PyCall or use Torch.jl, but still have a lot of work to do. The data loading and preprocessing could possibly be done much faster than in Python, so I'm experimenting with that a bit in julia. The ability to process large files is important, because in the end I would like to seamlessly process the entirety of Germany at 20-30cm resolution, so some TB. The output would be some other raster (or vector) file, so I don't really need chunked writes. I usually create a GDAL in memory dataset and write that out. But of course one could make that easier, too, allowing to write files larger than RAM.

> But GeoData.jl should do more to make information from DiskArrays.jl available from the GDALarray object if you need it anywhere - like if you need to know chunk sizes.

Yes, as I have lots of RAM available, the chunk sizes could be larger than what is used at the moment. I didn't find out how to change it yet, but I'm just at the start. Having loaded a big chunk, I can then process it in smaller chunks which fit onto the GPU - or just load the small chunks directly? I dont know yet. I'm looking at [TiledIteration](https://github.com/JuliaArrays/TiledIteration.jl) for that (which could [maybe replace DiskArray's internal chunking](https://github.com/meggart/DiskArrays.jl/issues/21)).

Finally another thing I have noticed: Timing getindex of a GDALarray and a RasterDataset gives different results.
```julia
using ArchGDAL
using GeoData

geoimg = GeoData.GDALarray("file")
archimg = ArchGDAL.readraster("file")

@time geoimg[1000:2000,  1000:2000, 2:8]
@time geoimg[2000:3000,  2000:3000, 2:8]
@time archimg[1000:2000, 1000:2000, 2:8]
@time archimg[2000:3000, 2000:3000, 2:8]

#  output of the second run:
#  1.150211 seconds (122 allocations: 13.382 MiB, 0.14% gc time)
#  1.360989 seconds (106 allocations: 13.382 MiB)
#  0.004321 seconds (22 allocations: 13.379 MiB)
#  0.004670 seconds (22 allocations: 13.379 MiB)
```
So indexing into the GDALarray is way slower. I haven't profiled yet, but maybe it's using some slow fallback routine or not utilizing the buffered chunks. So there is still work for our poor souls :D

**Comment by rafaqz** [comment]
Ok, will be good to have workloads that big to test this package out. Fast transfer of big 100GB/TB datsets to GPU memory is increasingly my main use-case too. But the time dimension breaks it into 1000s of separate slices so it's a different problem. 

The load time checks out. GeoData.jl doesn't leave hanging open files. Your `archimage` is an open file you need to close at some point. ArchGDAL discourages you from doing that too - it's better to do everything inside a `do` block. Maybe the second round is much faster for archgdal because the file is still open and cached by the os or something - it only hits disk the first time.

Mostly the way I use it GeoData I only load part the data once to memory so this point makes no real difference. But for multiple reads from an open file we will need a do-block syntax backed by the opened `RasterDataset`. That's not too hard to do, everything is already written like that underneath.

**Comment by maxfreu** [comment]
> The load time checks out. GeoData.jl doesn't leave hanging open files. Your `archimage` is an open file you need to close at some point. ArchGDAL discourages you from doing that too - it's better to do everything inside a `do` block. 

Yes, you are right. The overhead seems to come from opening and closing the file and I was unaware that I should use the do block.

>Maybe the second round is much faster for archgdal because the file is still open and cached by the os or something - it only hits disk the first time. Or maybe DiskArrays has caching?

[DiskArrays has caching](https://github.com/meggart/DiskArrays.jl/issues/15#issuecomment-611492021). But I'm unaware how it works and yet have to find out how to use it best. But I assume the speedup comes from there.

>Also I'm not sure what you mean by "with all its merits" - what is there that is lost by wrapping it and indexing into it? You can wrap a CuArray with a GeoArray and it still broadcasts on the GPU.

By merits I meant the caching behavior, but as you said, its lost by opening/closing what I was unaware of and didn't think it through.

**Comment by meggart** [comment]
> DiskArrays has caching. But I'm unaware how it works and yet have to find out how to use it best. But I assume the speedup comes from there.

In your example the caching does not come from DiskArrays, it rather comes from the underlying GDAL library. DiskArrays does not implement an explicit cache, all it does is to read data in efficient blocks when you apply high-level functions like sum or broadcast on them. I agree with @rafaqz that that GeoArrays should not inherit from AbstractDiskArray, but rather stay generic and be able to wrap any type of array (including DiskArrays, CuArrays and normal arrays etc.). 

So, when you index repeatedly into a DiskArray, the package will not help you speeding this up.

**Comment by rafaqz** [comment]
In terms of chunking, `AbstractDimArray` already defers broadcast to the parent type (ie for `CuArray`), so I get the feeling that 
you may already be able to just broadcast over it and `DiskArrays` will handle chunking without loading the whole file. The issue will be how to break up the side you are writing to into the same chunks.

Does that sound right @meggart ?

**Comment by maxfreu** [comment]
> In your example the caching does not come from DiskArrays, it rather comes from the underlying GDAL library.

>So, when you index repeatedly into a DiskArray, the package will not help you speeding this up.

Ahh ok! I didn't know that and was looking for the caching mechanism in DiskArrays without success.

>GeoArrays should not inherit from AbstractDiskArray

Yes, I agree as well; was just speculating what the reason for the time difference was.

**Comment by meggart** [comment]
Yes, this is correct. If you already defer broadcast, it might just work. Note that DiskArrays defines broadcast lazily, so an output will be returned instantaneously, you must call `copy` or `getindex` or friends to actually do the computation. 

Regarding output chunks, currently there is no fallback, so that all arrays participating in your broadcast call must have either have no chunks defined or align with the other defined chunks. Otherwise the broadcast call will error. So make sure to create the output arrays with the same chunks as your inputs.

**Comment by rafaqz** [comment]
Oh right broadcast will be chunk-wise if the source and dest align. That's great. I'll have to write some tests for doing this through an `AbstractGeoArray` wrapper.

It never ceases to amaze me how little we need to coordinate for this kind of thing to just work.
