### ISSUE TITLE
Don't show `GeoArray` data by default?

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/GeoData.jl#94]
Following #90 I was wondering whether it made sense to not show `GeoArray` data by default for `DiskGeoArray` and `MemGeoArray`?

Usually if I just type `ds[:speed]` at the REPL I want to see metadata about the `speed` field, but it always prints a huge array that fills the terminal (the specific numbers aren't that useful :P) and I need to scroll up to read the metadata I'm interested in.

As a side note, should showing a `MemGeoArray` take this much memory?

```julia
julia> using GeoData, NCDatasets

julia> ds = NCDstack("double_gyre.nc");

julia> u = ds[:u];

julia> typeof(u) |> supertype
MemGeoArray{Float32,4,Tuple{Dim{:xF,Array{Float64,1},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Float64},Intervals{Center}},NCDdimMetadata{String,Any}},Dim{:yC,Array{Float64,1},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Float64},Intervals{Center}},NCDdimMetadata{String,Any}},Dim{:zC,Array{Float64,1},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Regular{Float64},Intervals{Center}},NCDdimMetadata{String,Any}},Ti{Array{Float64,1},Sampled{Ordered{ForwardIndex,ForwardArray,ForwardRelation},Irregular{Tuple{Float64,Float64}},Intervals{Center}},NCDdimMetadata{String,Any}}},Array{Float32,4}}

julia> @benchmark show(u)

<...LOTS OF PRINTING...>

BenchmarkTools.Trial: 
  memory estimate:  7.89 MiB
  allocs estimate:  183289
  --------------
  minimum time:     128.102 ms (0.00% GC)
  median time:      143.703 ms (0.00% GC)
  mean time:        147.575 ms (0.53% GC)
  maximum time:     175.777 ms (4.29% GC)
  --------------
  samples:          34
  evals/sample:     1

```

**Comment by rafaqz** [comment]
Yeah maybe standardise on not showing the data.  In my experience Julias `show` is the least efficient part of the language, so im not surprised

**Comment by rafaqz** [comment]
So if you want to feel free update the `show` method to include all `AbstractGeoArray` and any other changes you think it needs. I pretty much wrote it just to fix a bug more than to be the best show method.

**Comment by ali-ramadhan** [comment]
I can do that!
